
import { Document, UserRole, User, MartyrProfile, Notification, IsargarCategory, AlborzCity, LanguageCode, TranslationStructure, HistoricalEvent } from './types';

export const localizeNumber = (num: string | number | undefined, lang: LanguageCode): string => {
    if (num === undefined || num === null) return '';
    const str = num.toString();
    if (['fa', 'ar', 'ku', 'bal'].includes(lang)) {
        const persianDigits = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
        return str.replace(/\d/g, x => persianDigits[parseInt(x)]);
    }
    return str;
};

// آمارهای واقعی سامانه یادگاران البرز
export const REAL_STATS = {
    totalIsargaran: 20702,
    totalMartyrs: 5250,
    totalJanbazan: 12400,
    totalAzadegan: 1052,
    totalDocuments: 145230,
    activeUsers: 48
};

export const MOCK_HISTORY: HistoricalEvent[] = [
    { day: 25, month: 12, title: 'عملیات خیبر', description: 'سالروز عملیات پیروزمندانه خیبر در جزایر مجنون.' },
    { day: 19, month: 10, title: 'عملیات کربلای ۵', description: 'سرسختانه‌ترین عملیات دفاع مقدس در منطقه شلمچه.' },
    { day: 31, month: 3, title: 'شهادت دکتر چمران', description: 'سالروز عروج ملکوتی سردار رشید اسلام دکتر مصطفی چمران در دهلاویه.' },
];

const EN_TRANSLATION: TranslationStructure = {
    appTitle: 'Yadegaran',
    appSubtitle: 'Comprehensive Veterans System',
    culturalUnit: 'Cultural Unit',
    foundationName: 'Alborz Martyrs Foundation',
    dashboard: 'Dashboard',
    archive: 'Smart Archive',
    restoration: 'Document Restoration',
    search: 'Advanced Search',
    aiProcessor: 'AI Processing',
    tags: 'Tag Management',
    users: 'Users & Access',
    reports: 'Statistics',
    settings: 'Settings',
    loginTitle: 'Yadegaran Smart System',
    loginSubtitle: 'Alborz Martyrs and Veterans Affairs Foundation',
    username: 'Username',
    password: 'Password',
    loginButton: 'Login',
    version: 'Version 2.5',
    logout: 'Logout',
    admin: 'System Admin',
    aiChatTitle: 'Yadegaran AI Assistant',
    aiChatWelcome: 'Hello! I am the Yadegaran AI assistant, serving the culture of sacrifice.',
    typeMessage: 'Type your message...',
    online: 'Online',
    placeholderTitle: 'Under Development',
    placeholderDesc: 'This section will be available soon.',
    menuGeneral: 'General',
    menuSmartArchive: 'Smart Archive',
    menuStrategic: 'Strategic Sections',
    menuBaseInfo: 'Base Information',
    sloganSaadi: 'He who learns not from the passing of days, learns from no teacher.',
    sloganRazm: 'The battle is better written by the pen.',
    statsProfiles: 'Veterans Profiles',
    statsDocs: 'Digital Documents',
    statsUsers: 'System Users',
    statsStatus: 'Service Status',
    chartDocsTrend: 'Document Input Trend',
    chartCategories: 'Target Group Category',
    chartMedia: 'Media Diversity',
    recentActivity: 'Recent Activity',
    newFile: 'Create New Profile',
    addDoc: 'Add New Document',
    searchPlaceholder: 'Search name, ID, or file...',
    noDocs: 'No documents registered for this profile.',
    langCatNative: 'Native Language',
    langCatResistance: 'Resistance Languages',
    langCatRegional: 'Regional Languages',
    langCatIntl: 'International Languages',
    razmanNovin: 'Modern Warriors',
    catNuclear: 'Nuclear Energy Heroes',
    cat12DayWar: 'Heroes of 12-Day War',
    catModernEra: 'Modern Era Warriors',
    catRegional: 'Regional Champions',
    subDanayan: 'Martyred Scientists',
    subNegahbanan: 'Secret Keepers (Security)',
    subCyberSoldiers: 'Cyber Soldiers',
    subTirandazan: 'Quds Missile Units',
    subCheshmha: 'Awake Eyes (Intel)',
    subJangavaran: 'Virtual Warriors',
    subZabanha: 'Expressive Tongues (Media)',
    subSoftWar: 'Soft War',
    subMediaWar: 'Media War',
    subDiplomacy: 'Resistance Diplomacy',
    subEconomy: 'Resistance Economy',
    subYemen: 'Lions of Yemen',
    subSyria: 'Heroes of Syria',
    subLebanon: 'Warriors of Lebanon',
    subIraq: 'Riders of Iraq',
    subPalestine: 'Mujahideen of Palestine',
    hooshmandNegar: 'Smart AI Generation',
    farazJavidan: 'Faraz-e Javidan',
    secHeroes: 'Gallery of Heroes',
    subRazmNegasht: 'Combat Art Gallery',
    subAudioBio: 'Audio Biography',
    subDigitalStatue: 'Digital Statues',
    subFamilyGallery: 'Family Gallery',
    subInteractiveMemorial: 'Interactive Memorials',
    secEncyclopedia: 'Encyclopedia of Razm',
    subCultureDict: 'Combat Dictionary',
    subOpsEncyclopedia: 'Encyclopedia of Ops',
    subTacticsLib: 'Tactics Library',
    subWeaponsInfo: 'Weapons Info',
    subRazmGeo: 'Combat Geography',
    secTraining: 'Training Ground',
    subModernCombat: 'Modern Combat Training',
    subOpsSim: 'Operations Simulator',
    subSpecialExams: 'Specialized Exams',
    subCertificates: 'Combat Certificates',
    subSkillRank: 'Skill Ranking',
    secSecrets: 'Hall of Secrets',
    subSpecialDocs: 'Special Documents',
    subConfidentialReports: 'Confidential Reports',
    subStratAnalysis: 'Strategic Analysis',
    subOpsMaps: 'Operation Maps',
    subSecretStats: 'Secret Statistics',
    secForum: 'Warriors Forum',
    subSpecialCircles: 'Specialized Circles',
    subWarriorsChat: 'Warriors Chat',
    subOpsCoord: 'Ops Coordination',
    subCommNetwork: 'Communication Network',
    subConsultRooms: 'Consultation Rooms',
    revayatTitle: 'Unfinished Narrative',
    revayatSubtitle: 'Record and store oral memories',
    speakVasiat: 'Listen to the Will',
    semanticSearch: 'Semantic Search'
};

export const TRANSLATIONS: Record<LanguageCode, TranslationStructure> = {
    fa: {
        appTitle: 'یادگاران البرز',
        appSubtitle: 'سامانه هوشمند مدیریت اسناد ایثارگران',
        culturalUnit: 'واحد فرهنگی',
        foundationName: 'بنیاد شهید استان البرز',
        dashboard: 'داشبورد مدیریتی',
        archive: 'آرشیو هوشمند اسناد',
        restoration: 'ترمیم و تجلی اسناد',
        search: 'جستجوی پیشرفته',
        aiProcessor: 'پردازش هوشمند (AI)',
        tags: 'مدیریت تگ‌ها',
        users: 'کاربران و دسترسی‌ها',
        reports: 'گزارشات آماری',
        settings: 'تنظیمات سامانه',
        loginTitle: 'سامانه هوشمند یادگاران',
        loginSubtitle: 'بنیاد شهید و امور ایثارگران استان البرز',
        username: 'نام کاربری',
        password: 'کلمه عبور',
        loginButton: 'ورود به سامانه',
        version: 'نسخه ۲.۵',
        logout: 'خروج',
        admin: 'مدیر سیستم',
        aiChatTitle: 'دستیار هوشمند یادگاران',
        aiChatWelcome: 'سلام! من دستیار هوشمند سامانه یادگاران هستم. در خدمت فرهنگ ایثار و شهادت استان البرز.',
        typeMessage: 'پیام خود را بنویسید...',
        online: 'آنلاین',
        placeholderTitle: 'بخش در حال توسعه',
        placeholderDesc: 'این بخش به زودی در دسترس خواهد بود.',
        menuGeneral: 'پیشخوان البرز',
        menuSmartArchive: 'آرشیو هوشمند',
        menuStrategic: 'بخش‌های راهبردی',
        menuBaseInfo: 'اطلاعات پایه',
        sloganSaadi: `همه روی یکسر به جنگ آوریم        جهان بر بد اندیش تنگ آوریم\nهمه سر به سر تن به کشتن دهیم     از آن به که کشور به دشمن دهیم\nچنین گفت موبد که مردن به نام        به از زنده ، دشمن بدو شادکام\nچو ایران نباشد تن من مباد           بر این بوم و بر زنده یک تن مباد`,
        sloganRazm: 'رزم آن به که نوشته شود به قلم',
        statsProfiles: 'پرونده‌های ایثارگران',
        statsDocs: 'اسناد دیجیتال',
        statsUsers: 'کاربران سامانه',
        statsStatus: 'وضعیت سرویس‌ها',
        chartDocsTrend: 'روند ورودی اسناد',
        chartCategories: 'دسته‌بندی جامعه هدف',
        chartMedia: 'تنوع رسانه‌ای اسناد',
        recentActivity: 'فعالیت‌های اخیر',
        newFile: 'تشکیل پرونده جدید',
        addDoc: 'افزودن سند جدید',
        searchPlaceholder: 'جستجوی نام، پرونده، سال، تگ یا محتوا...',
        noDocs: 'هیچ سندی برای این پرونده ثبت نشده است.',
        langCatNative: 'زبان مادری',
        langCatResistance: 'زبان مقاومت',
        langCatRegional: 'زبان‌های منطقه',
        langCatIntl: 'زبان‌های بین‌المللی',
        razmanNovin: 'رزمـــان نوین',
        catNuclear: 'پهلوانان انرژی هسته‌ای',
        cat12DayWar: 'دلاوران جنگ ۱۲ روزه',
        catModernEra: 'رزمندگان عصر نوین',
        catRegional: 'یلان منطقه',
        subDanayan: 'دانایان شهید (دانشمندان)',
        subNegahbanan: 'نگهبانان اسرار (امنیتی)',
        subCyberSoldiers: 'سربازان سایبری',
        subTirandazan: 'تیراندازان قدس (موشکی)',
        subCheshmha: 'چشم‌های بیدار (اطلاعاتی)',
        subJangavaran: 'جنگاوران مجازی (سایبری)',
        subZabanha: 'زبان‌های گویا (رسانه‌ای)',
        subSoftWar: 'نبرد نرم',
        subMediaWar: 'نبرد رسانه‌ای',
        subDiplomacy: 'دیپلماسی مقاومت',
        subEconomy: 'اقتصاد مقاومتی',
        subYemen: 'شیران یمن',
        subSyria: 'پهلوانان سوریه',
        subLebanon: 'دلاوران لبنان',
        subIraq: 'سواران عراق',
        subPalestine: 'مجاهدان فلسطین',
        hooshmandNegar: 'هوشمند نگارالبرز',
        farazJavidan: 'فراز جاویدان',
        secHeroes: 'تالار پهلوانان',
        subRazmNegasht: 'رزم‌نگاشت‌ها',
        subAudioBio: 'زندگینامه گویا',
        subDigitalStatue: 'تندیس‌های دیجیتال',
        subFamilyGallery: 'گالری خانوادگی',
        subInteractiveMemorial: 'یادبودهای تعاملی',
        secEncyclopedia: 'دانش‌نامه رزم',
        subCultureDict: 'فرهنگ‌نامه رزمی',
        subOpsEncyclopedia: 'دانش‌نامه عملیات',
        subTacticsLib: 'کتابخانه تاکتیک‌ها',
        subWeaponsInfo: 'آشنایی با سلاح‌ها',
        subRazmGeo: 'جغرافیای رزم',
        secTraining: 'میدان آموزش',
        subModernCombat: 'آموزش‌های رزم نوین',
        subOpsSim: 'شبیه‌ساز عملیات',
        subSpecialExams: 'آزمون‌های تخصصی',
        subCertificates: 'گواهینامه رزمی',
        subSkillRank: 'رده‌بندی مهارت‌ها',
        secSecrets: 'تالار اسرار',
        subSpecialDocs: 'اسناد ویژه',
        subConfidentialReports: 'گزارش‌های محرمانه',
        subStratAnalysis: 'تحلیل‌های استراتژیک',
        subOpsMaps: 'نقشه‌های عملیاتی',
        subSecretStats: 'آمارهای سری',
        secForum: 'انجمن رزم‌آوران',
        subSpecialCircles: 'حلقه‌های تخصصی',
        subWarriorsChat: 'گفت‌وگوی رزم‌آوران',
        subOpsCoord: 'هماهنگی عملیات',
        subCommNetwork: 'شبکه ارتباطی',
        subConsultRooms: 'اتاق‌های مشاوره',
        revayatTitle: 'روایت ناتمام',
        revayatSubtitle: 'ثبت و آرشیو خاطرات شفاهی',
        speakVasiat: 'شنیدن وصیت‌نامه (AI)',
        semanticSearch: 'جستجوی هوشمند معنایی'
    },
    en: EN_TRANSLATION,
    ar: EN_TRANSLATION,
    tr: EN_TRANSLATION,
    ku: EN_TRANSLATION,
    bal: EN_TRANSLATION,
    ru: EN_TRANSLATION,
    zh: EN_TRANSLATION,
    es: EN_TRANSLATION,
};

export const SAMPLE_TAGS = [
    'دفاع مقدس', 'عملیات کربلای ۵', 'عملیات والفجر ۸', 'شهدای غواص', 'مدافعان حرم',
    'آزادگان سرافراز', 'جانبازان شیمیایی', 'خاطرات جنگ', 'وصیت‌نامه', 'دست‌نوشته',
    'عکس پرسنلی', 'منطقه عملیاتی جنوب', 'غرب کشور', 'اسناد پزشکی', 'نامه به خانواده',
    'مصاحبه', 'سخنرانی', 'تشییع جنازه', 'اعزام به جبهه', 'پشتیبانی جنگ',
    'شهدای هسته‌ای', 'شهدای امنیت', 'مقاومت اسلامی', 'قدس', 'اربعین'
];

export const MOCK_USERS: User[] = [
    { id: 1, name: 'مدیر سیستم', username: 'admin', role: 'ADMIN', avatar: 'https://lh3.googleusercontent.com/d/18oO9ea3mBJBGQZYonKWxZ9VIxRZAIC8f', status: 'active', lastLogin: '14:30 امروز' },
    { id: 2, name: 'سارا احمدی', username: 'sahmadi', role: 'EXPERT', avatar: '', status: 'active', lastLogin: 'دیروز' },
];

export const MOCK_PROFILES: MartyrProfile[] = [
    {
        id: 'P-1402001',
        name: 'مهدی',
        family: 'باکری',
        fatherName: 'فیض‌الله',
        nationalCode: '1234567890',
        gender: 'مرد',
        birthDate: '1333/01/30',
        martyrdomDate: '1363/12/25',
        province: 'آذربایجان غربی', 
        city: 'سایر', 
        bio: 'مهدی باکری فرمانده لشکر ۳۱ عاشورا بود. او در عملیات‌های فتح‌المبین، بیت‌المقدس، رمضان، مسلم بن عقیل، والفجر مقدماتی، والفجر ۱، ۲، ۳ و ۴ و عملیات خیبر شرکت کرد.',
        avatar: 'https://lh3.googleusercontent.com/d/1t7mux4ec-aINM_TKukyi6Wr1yhTNYLbl',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        razmanCategory: 'modern',
        unit: 'لشکر ۳۱ عاشورا'
    },
    {
        id: 'P-1402002',
        name: 'محمد ابراهیم',
        family: 'همت',
        fatherName: 'علی‌اکبر',
        nationalCode: '0041234567',
        gender: 'مرد',
        birthDate: '1334',
        martyrdomDate: '1362/12/24',
        province: 'اصفهان',
        city: 'شهرضا',
        bio: 'محمد ابراهیم همت از فرماندهان ارشد سپاه پاسداران در جنگ ایران و عراق بود. او فرماندهی لشکر ۲۷ محمد رسول‌الله را بر عهده داشت و در عملیات خیبر به شهادت رسید.',
        avatar: 'https://lh3.googleusercontent.com/d/1NrR4zi4Bynkjsslh0QYPCmFff5UIANDa',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        razmanCategory: 'modern',
        unit: 'لشکر ۲۷ محمد رسول‌الله'
    },
    {
        id: 'P-1402003',
        name: 'مرتضی',
        family: 'آوینی',
        fatherName: 'سید مهدی',
        nationalCode: '0059876543',
        gender: 'مرد',
        birthDate: '1326/06/21',
        martyrdomDate: '1372/01/20',
        province: 'تهران',
        city: 'سایر',
        bio: 'سید مرتضی آوینی مستندساز، عکاس، روزنامه‌نگار، نویسنده و نظریه‌پرداز سینمای اسلامی ایرانی بود. وی در فکه بر اثر انفجار مین به شهادت رسید.',
        avatar: 'https://lh3.googleusercontent.com/d/1tuptvInjEUG2QdRISjf6oL5nvuuhdctv',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        razmanCategory: 'zabanha',
        unit: 'روایت فتح'
    },
    {
        id: 'P-1402004',
        name: 'قاسم',
        family: 'سلیمانی',
        fatherName: 'حسن',
        nationalCode: '2991234567',
        gender: 'مرد',
        birthDate: '1335/12/20',
        martyrdomDate: '1398/10/13',
        province: 'کرمان',
        city: 'سایر',
        bio: 'قاسم سلیمانی فرمانده نیروی قدس سپاه پاسداران انقلاب اسلامی بود. او در طول جنگ ایران و عراق و پس از آن فرماندهی عملیات‌های متعددی را برعهده داشت.',
        avatar: 'https://lh3.googleusercontent.com/d/1VN59_XTRDJk8PTiGwivCNK5pWK0cc9aX',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.RESISTANCE,
        razmanCategory: 'regional',
        unit: 'سپاه قدس'
    },
    {
        id: 'P-1402005',
        name: 'یدالله',
        family: 'کلهر',
        fatherName: 'محمد',
        nationalCode: '4890012345',
        gender: 'مرد',
        birthDate: '1333',
        martyrdomDate: '1365/11/01',
        province: 'البرز',
        city: 'کرج',
        bio: 'شهید یدالله کلهر قائم‌مقام لشکر ۱۰ سیدالشهدا (ع) و از اسطوره‌های دفاع مقدس در استان البرز بود. او در عملیات کربلای ۵ به شهادت رسید.',
        avatar: 'https://lh3.googleusercontent.com/d/1z5tgYfeF3eh7no6gqgwFL149F9zCR2X7',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        unit: 'لشکر ۱۰ سیدالشهدا'
    },
    {
        id: 'P-1008996',
        name: 'غلامرضا',
        family: 'ابراهیم فرد',
        fatherName: 'علی',
        nationalCode: '1008996',
        gender: 'مرد',
        birthDate: '1347/01/09',
        martyrdomDate: '1367/05/02',
        education: 'دوم راهنمایی',
        province: 'البرز',
        city: 'کرج',
        burialPlace: 'کرج روستای گرمدره',
        bio: 'شغل: آهن فروشی. وضعیت تاهل: مجرد. نحوه شهادت: در اثر حوادث جنگی در حاج عمران. شماره پرونده: 436/67.',
        avatar: 'https://lh3.googleusercontent.com/d/18KcT1a96b8Ewu89E6y3LvVYf4hgCh9K8',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        unit: 'لشگر 164 گردان 167 - ارتش'
    },
    {
        id: 'P-1009594',
        name: 'تقی',
        family: 'ابراهیم',
        fatherName: 'علی شیر',
        nationalCode: '1009594',
        gender: 'مرد',
        birthDate: '1354/06/20',
        martyrdomDate: '1362/11/29',
        education: 'سوم راهنمایی',
        province: 'البرز',
        city: 'کرج',
        burialPlace: 'طالقان – روستای خچیره',
        bio: 'شهید تقی ابراهیم در سال ۱۳۵۴ در روستای خچیره طالقان متولد شد. او دوران ابتدایی و راهنمایی را در روستا گذراند و همزمان با شروع انقلاب فعالیت‌های مذهبی و سیاسی خود را آغاز کرد. وی برای ادامه تحصیل به کرج آمد و در کنار تحصیل به کار و ورزش رزمی مشغول شد. سرانجام پس از اعزام به جبهه غرب، در تاریخ ۲۹/۱۱/۶۲ در درگیری با ضدانقلاب در بوکان به شهادت رسید. شماره پرونده: 612/62.',
        avatar: 'https://lh3.googleusercontent.com/d/1gYogV4vjxgZaeFiWSNbuPzOQeZ52MCiv',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        unit: 'بسیج'
    },
    {
        id: 'P-1402006',
        name: 'یدالله',
        family: 'ابراهیمی',
        fatherName: 'اکبر',
        nationalCode: '1402006',
        gender: 'مرد',
        birthDate: '1333/10/02',
        martyrdomDate: '1361/07/09',
        province: 'البرز',
        city: 'کرج',
        burialPlace: 'مفقودالاثر',
        bio: 'شغل: نقاش اتومبیل. محل شهادت: سومار. عملیات: مسلم بن عقیل. شهید یدالله ابراهیمی در خانواده‌ای مذهبی و مستضعف متولد شد. پدرش از معلمان مذهبی در قم و نجف بود. وی از کودکی با تربیت مکتب اسلام رشد کرد و برای کمک به معیشت خانواده به کارگری و سپس نقاشی اتومبیل مشغول شد. او از پیروان راستین امام خمینی (ره) بود و با شروع جنگ، علیرغم فشارهای صاحب‌کار، برای دفاع از وطن و با آرزوی زیارت کربلا عازم جبهه‌ شد. سرانجام در عملیات مسلم بن عقیل در منطقه سومار مفقودالاثر گشت. شعار همیشگی ایشان: خدایا خدایا تا انقلاب مهدی خمینی را نگهدار.',
        avatar: 'https://lh3.googleusercontent.com/d/1TOdQWd7ipZjWEqDQ7Vd06SHjh48XyljL',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        unit: 'بسیج'
    },
    {
        id: 'P-1011940',
        name: 'هوشنگ',
        family: 'ابراهیمی پنجکی',
        fatherName: 'شکراله',
        nationalCode: '1011940',
        gender: 'مرد',
        birthDate: '1337',
        martyrdomDate: '1365',
        education: 'دیپلم طبیعی',
        province: 'البرز',
        city: 'کرج',
        bio: 'شغل: کارمند شرکت نفت. محل شهادت: شلمچه. عملیات: کربلای ۵. نحوه شهادت: اصابت ترکش خمپاره به سینه و پا. شهید هوشنگ ابراهیمی در خانواده‌ای مذهبی در نوشهر متولد شد و تحصیلات متوسطه را در کرج به پایان رساند. او دوران سربازی خود را در نیروی هوایی ارتش و در جبهه‌ها سپری کرد. پس از استخدام در شرکت نفت، در واحد کارگزینی فعال بود و از اعضای فعال بسیج کارکنان محسوب می‌شد. ایشان فردی قانع، ساده‌زیست و پایبند به واجبات بود. سرانجام در سال ۱۳۶۵ به صورت داوطلبانه به جبهه‌های جنوب اعزام و در منطقه شلمچه به مقام رفیع شهادت نائل آمد.',
        avatar: 'https://lh3.googleusercontent.com/d/1r87JCRwr_Vv3ehr_mNmJ8ngxgKfVRle6',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        unit: 'بسیج کارکنان شرکت نفت - سپاه'
    },
    {
        id: 'P-1402007',
        name: 'قدرت‌الله',
        family: 'ابراهیمی پنجکی',
        fatherName: 'فتح‌الله',
        nationalCode: '1402007',
        gender: 'مرد',
        birthDate: '1341/07/20',
        martyrdomDate: '1361/07/12',
        education: 'دوم راهنمایی',
        province: 'البرز',
        city: 'کرج',
        burialPlace: 'گلزار شهدای آشیر',
        bio: 'شغل: کارگر کارخانه پارچه‌بافی کرج. محل شهادت: سومار. عملیات: پدافندی. نحوه شهادت: اصابت ترکش به ناحیه سر و پا. شهید قدرت‌الله ابراهیمی در سال ۱۳۴۱ در نوشهر متولد شد. ایشان به عنوان کارگر در کارخانه پارچه‌بافی کرج مشغول به کار بود. با شروع جنگ تحمیلی، از طریق بسیج به جبهه‌ها اعزام شد و به عنوان رزمنده در جبهه حضور داشت. سرانجام پس از دو ماه حضور خالصانه در جبهه، در تاریخ ۱۳۶۱/۰۷/۱۲ در منطقه سومار به فیض شهادت نائل آمد و پیکر مطهرش در گلزار شهدای آشیر به خاک سپرده شد.',
        avatar: 'https://lh3.googleusercontent.com/d/1DYL-Ui_xl22CLAaO-c_hEI3hESmPv1Oi',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        unit: 'بسیج'
    },
    {
        id: 'P-1402008',
        name: 'امان‌الله',
        family: 'ابراهیمی پنجکی',
        fatherName: 'علی',
        nationalCode: '1402008',
        gender: 'مرد',
        birthDate: '1345/03/10',
        martyrdomDate: '1361/08/11',
        education: 'دوم راهنمایی',
        province: 'البرز',
        city: 'کرج',
        burialPlace: 'چالوس روستای پنجک',
        bio: 'شغل: محصل. محل شهادت: سومار. عملیات: محرم. نحوه شهادت: اصابت ترکش و تیر. شهید امان‌الله ابراهیمی در سال ۱۳۴۵ در روستای پنجک مازندران متولد شد. ایشان به عنوان محصل به تحصیل اشتغال داشت. با شروع جنگ تحمیلی، از طریق بسیج به جبهه‌ها اعزام شد. سرانجام پس از ۴۵ روز حضور حماسی در جبهه، در تاریخ ۱۳۶۱/۰۸/۱۱ در عملیات محرم در منطقه سومار به فیض شهادت نائل آمد و پیکر مطهرش در روستای پنجک چالوس به خاک سپرده شد.',
        avatar: 'https://lh3.googleusercontent.com/d/1dnGu1AB9AO25zb1A9D_tLe_77TPXFmNU',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        unit: 'بسیج'
    },
    {
        id: 'P-1012476',
        name: 'محمد',
        family: 'ابراهیمی تکمه داش',
        fatherName: 'حسین',
        nationalCode: '1012476',
        gender: 'مرد',
        birthDate: '1344/01/05',
        martyrdomDate: '1363/12/17',
        education: 'پنجم ابتدایی',
        province: 'البرز',
        city: 'کرج',
        burialPlace: 'بی‌مزار (جاویدالاثر)',
        bio: 'شغل: پاسدار سپاه. محل شهادت: شرق دجله. نحوه شهادت: مفقودیت در اثر درگیری با دشمن بعثی. شهید محمد ابراهیمی در تبریز متولد شد و فرزند سوم خانواده بود. او در کارهای چراغ‌سازی در کرج به پدرش کمک می‌کرد. پس از اتمام مقطع ابتدایی به دلیل سختی زندگی به کارگری روی آورد. با عشق به انقلاب وارد بسیج و سپس سپاه شد. در اواسط سال ۶۳ به جبهه‌های جنوب اعزام گردید و سرانجام در تاریخ ۱۷ اسفند ۶۳ در منطقه شرق دجله به فیض شهادت نائل آمد و پیکر مطهرش هنوز به میهن بازنگشته است. ایشان فردی صبور، مهربان و فداکار نسبت به خانواده بود.',
        avatar: 'https://lh3.googleusercontent.com/d/1A_3JoW0odIB6CQWM2KHAj8uS0jDHVn3t',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        unit: 'سپاه پاسداران انقلاب اسلامی'
    },
    {
        id: 'P-1402009',
        name: 'محمدتقی',
        family: 'ابراهیمی',
        fatherName: 'احمد',
        nationalCode: '1402009',
        gender: 'مرد',
        birthDate: '1344',
        martyrdomDate: '1361/02/10',
        education: 'اول دبیرستان (حسابداری)',
        province: 'البرز',
        city: 'کرج',
        burialPlace: 'بهشت زهرا',
        bio: 'شغل: محصل. محل شهادت: فکه. عملیات: بیت‌المقدس. نحوه شهادت: مفقود - متلاشی شدن پیکر. شهید محمدتقی ابراهیمی در سال ۱۳۴۴ در بهشهر متولد شد. ایشان دانش‌آموز سال اول دبیرستان در رشته حسابداری بود که از طریق بسیج به جبهه اعزام شد. وی در تیپ محمد رسول‌الله (ص) به عنوان رزمنده فعالیت می‌کرد. سرانجام در تاریخ ۱۰ اردیبهشت ۱۳۶۱ در جریان عملیات غرورآفرین بیت‌المقدس در منطقه فکه به مقام رفیع شهادت نائل آمد و پیکر مطهرش در بهشت زهرا (س) به خاک سپرده شد.',
        avatar: 'https://lh3.googleusercontent.com/d/1LUCcoDxgCEF3hOgstqaUVHHmpSKtGyno',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        unit: 'تیپ محمد رسول‌الله (ص) - بسیج'
    },
    {
        id: 'P-1013306',
        name: 'عباس',
        family: 'ابراهیمی میاندهی',
        fatherName: 'محمود',
        nationalCode: '1013306',
        gender: 'مرد',
        birthDate: '1347/08/05',
        martyrdomDate: '1365/10/26',
        education: 'پنجم ابتدایی',
        province: 'البرز',
        city: 'کرج',
        bio: 'شغل: سپاهی (پاسدار وظیفه). محل شهادت: شلمچه. عملیات: کربلای ۵. نحوه شهادت: اصابت ترکش خمپاره. شهید عباس ابراهیمی در میانده رشت متولد شد. ایشان به عنوان پاسدار وظیفه در جبهه‌های نبرد حق علیه باطل حضور یافت. سرانجام در تاریخ ۲۶ دی ماه ۱۳۶۵ در جریان عملیات گسترده کربلای ۵ در منطقه عملیاتی شلمچه بر اثر اصابت ترکش خمپاره به فیض عظیم شهادت نائل آمد. آخرین مسئولیت ایشان در جبهه رزمنده بود.',
        avatar: 'https://lh3.googleusercontent.com/d/10U7WN9C-7P_Tb4fq2LVC6ObY_nVhXScT',
        status: 'فعال',
        isVerified: true,
        category: IsargarCategory.MARTYR,
        unit: 'سپاه پاسداران انقلاب اسلامی'
    }
];

export const MOCK_DOCUMENTS: Document[] = [
    { id: '1', title: 'وصیت‌نامه دستی', type: 'image', category: 'وصیت‌نامه', date: '1402/05/10', status: 'processed', tags: ['وصیت‌نامه', 'دفاع مقدس'], profileId: 'P-1402001', thumbnail: 'https://media.mehrnews.com/d/2016/03/15/4/2026573.jpg', description: 'تصویر دست‌نوشته وصیت‌نامه شهید باکری' },
    { id: '2', title: 'فیلم مصاحبه قبل از عملیات', type: 'video', category: 'خاطرات', date: '1402/06/15', status: 'processed', tags: ['مصاحبه', 'عملیات خیبر'], profileId: 'P-1402001', description: 'فیلم مصاحبه با رزمندگان لشکر عاشورا' },
    { id: '3', title: 'مدارک تحصیلی', type: 'pdf', category: 'مدارک', date: '1401/10/01', status: 'processed', tags: ['دانشگاه', 'تحصیلات'], profileId: 'P-1402002', description: 'اسکن مدارک دکترای فیزیک پلاسما از آمریکا' },
    { id: '5', title: 'گزارش محرمانه', type: 'text', category: 'نامه اداری', date: '1403/02/20', status: 'processed', tags: ['محرمانه', 'مکاتبات'], profileId: 'P-1402004', description: 'نامه اداری مربوط به عملیات برون مرزی' },
    { id: '6', title: 'عکس پرسنلی', type: 'image', category: 'تصاویر', date: '1367/05/02', status: 'processed', tags: ['عکس پرسنلی', 'کرج'], profileId: 'P-1008996', thumbnail: 'https://lh3.googleusercontent.com/d/18KcT1a96b8Ewu89E6y3LvVYf4hgCh9K8', description: 'تصویر پرسنلی شهید غلامرضا ابراهیم فرد' },
    { id: '7', title: 'عکس پرسنلی', type: 'image', category: 'تصاویر', date: '1362/11/29', status: 'processed', tags: ['عکس پرسنلی', 'کرج'], profileId: 'P-1009594', thumbnail: 'https://lh3.googleusercontent.com/d/1gYogV4vjxgZaeFiWSNbuPzOQeZ52MCiv', description: 'تصویر پرسنلی شهید تقی ابراهیم' },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
    { id: 1, type: 'system', message: 'خوش آمدید! نسخه ۲.۵ سامانه یادگاران البرز بارگذاری شد.', time: 'همین الان', read: false },
    { id: 2, type: 'ai', message: 'پردازش هوشمند سند "وصیت‌نامه دستی" تکمیل شد.', time: '۵ دقیقه پیش', read: false },
];

export const ACTIVITY_LOGS = [
    { id: 1, action: 'ورود به سیستم', user: 'مدیر سیستم', time: '14:30', type: 'info' },
];
